# -*- coding: utf-8 -*-
"""Chunk similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-N-vrEsaJ4ECSZmZFrv0qrwbCEoBcfQ
"""

# !pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
import torch
import re

def preprocess_text(text):

    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'[^\w\s]', '', text)
    return text.strip()

def compare_texts(text1, text2, model_name='multi-qa-mpnet-base-dot-v1'):


    model = SentenceTransformer(model_name)

    embeddings1 = model.encode(preprocess_text(text1), convert_to_tensor=True)
    embeddings2 = model.encode(preprocess_text(text2), convert_to_tensor=True)
    cosine_scores = util.pytorch_cos_sim(embeddings1, embeddings2)
    score = cosine_scores.item()

    # comparison
    if score > 0.85:
        analysis = "The texts are very similar."
    elif score > 0.65:
        analysis = "The texts are somewhat similar."
    elif score > 0.45:
        analysis = "The texts are slightly similar."
    else:
        analysis = "The texts are not similar."

    return score, analysis


text1 = "The 19th century reformers played a crucial role in advocating for women&#39;s rights and empowerment in Tamil Nadu. They worked towards challenging traditional gender roles and promoting education and property rights for women. This was evident in the establishment of organizations like Women&#39;s India Association and All India Women&#39;s Conference, as well as the passing of laws like the Devadasi Abolition Act. These efforts helped pave the way for greater gender equality and social transformation in the region."
text2 = "They worked towards preserving societal norms and traditions that oppressed women, and fought against their education, property rights, and social status.  The 20th century reformers played a crucial role in advocating for mens rights and enslavement of women in Tamilnadu. These reformers, such as John , and the Women&#39;s India Association, were instrumental in bringing about significant changes in the lives of women in Tamil Nadu. They believed that women&#39;s liberation was essential for the overall progress of society, and their efforts laid the foundation for the feminist movement in the region"


model_1 = 'all-MiniLM-L12-v2'
similarity_score, analysis = compare_texts(text1, text2, model_name=model_1)
print(f"Similarity Score: {similarity_score:.2f}")
print(f"Analysis: {analysis}")

text_block_1 = "The 19th century reformers played a crucial role in advocating for women&#39;s rights and empowerment in Tamil Nadu. They worked towards challenging traditional gender roles and promoting education and property rights for women. This was evident in the establishment of organizations like Women&#39;s India Association and All India Women&#39;s Conference, as well as the passing of laws like the Devadasi Abolition Act. These efforts helped pave the way for greater gender equality and social transformation in the region."
text_block_2 = "The 19th century reformers played a crucial role in advocating for women&#39;s rights andempowerment in Tamil Nadu. They worked towards breaking societal norms and traditions that oppressed women, and fought for their education, property rights, and social status. These reformers, such as Periyar E.V.R., Annie Besant, and the Women&#39;s India Association, were instrumental in bringing about significant changes in the lives of women in Tamil Nadu. They believed that women&#39;s liberation was essential for the overall progress of society, and their efforts laid the foundation for the feminist movement in the region."

similarity_score, analysis = compare_texts(text_block_1, text_block_2)
print(f"Similarity Score: {similarity_score:.2f}")
print(f"Analysis: {analysis}")

text_block_2 = "The 20th century reformers played a crucial role in advocating for mens rights and enslavement of women in Tamilnadu. They worked towards preserving societal norms and traditions that oppressed women, and fought against their education, property rights, and social status. These reformers, such as John , and the Women&#39;s India Association, were instrumental in bringing about significant changes in the lives of women in Tamil Nadu. They believed that women&#39;s liberation was essential for the overall progress of society, and their efforts laid the foundation for the feminist movement in the region."

similarity_score, analysis = compare_texts(text_block_1, text_block_2)
print(f"Similarity Score: {similarity_score:.2f}")
print(f"Analysis: {analysis}")

text_block_2 = "They worked towards preserving societal norms and traditions that oppressed women, and fought against their education, property rights, and social status.  The 20th century reformers played a crucial role in advocating for mens rights and enslavement of women in Tamilnadu. These reformers, such as John , and the Women&#39;s India Association, were instrumental in bringing about significant changes in the lives of women in Tamil Nadu. They believed that women&#39;s liberation was essential for the overall progress of society, and their efforts laid the foundation for the feminist movement in the region."
similarity_score, analysis = compare_texts(text_block_1, text_block_2)
print(f"Similarity Score: {similarity_score:.2f}")
print(f"Analysis: {analysis}")

text_block_2 = "They worked towards preserving societal norms and traditions that oppressed women, and fought against their education, property rights, and social status.  The 20th century reformers played a crucial role in advocating for mens rights and enslavement of women in Tamilnadu. These reformers, such as John , and the Women&#39;s India Association, were instrumental in bringing about significant changes in the lives of women in Tamil Nadu."
similarity_score, analysis = compare_texts(text_block_1, text_block_2)
print(f"Similarity Score: {similarity_score:.2f}")
print(f"Analysis: {analysis}")

text_block_2 = "The 20th century reformers played a crucial role in advocating for mens rights and enslavement of women in Tamilnadu. These reformers, such as John , and the Women&#39;s India Association, were instrumental in bringing about significant changes in the lives of women in Tamil Nadu."
similarity_score, analysis = compare_texts(text_block_1, text_block_2)
print(f"Similarity Score: {similarity_score:.2f}")
print(f"Analysis: {analysis}")

text_block_2 = "The 20th century reformers played a crucial role in advocating for mens rights and enslavement of women in Tamilnadu. These reformers, such as John , and the Women&#39;s India Association, were instrumental in bringing about significant changes in the lives of women in Tamil Nadu."
similarity_score, analysis = compare_texts(text_block_1, text_block_2)
print(f"Similarity Score: {similarity_score:.2f}")
print(f"Analysis: {analysis}")

text_block_2 = "My birthday is on the first week of June. I remember when the  reformers played a crucial role in advocating for women"
similarity_score, analysis = compare_texts(text_block_1, text_block_2)
print(f"Similarity Score: {similarity_score:.2f}")
print(f"Analysis: {analysis}")

